# Flight Price Prediction ✈️

In [25]:
# Step 1: Import Required Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [26]:
# Step 2: Load the Dataset
df = pd.read_excel('Data_Train.xlsx')

In [27]:
# Step 3: Data Exploration
df.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  object
 1   Date_of_Journey  10683 non-null  object
 2   Source           10683 non-null  object
 3   Destination      10683 non-null  object
 4   Route            10682 non-null  object
 5   Dep_Time         10683 non-null  object
 6   Arrival_Time     10683 non-null  object
 7   Duration         10683 non-null  object
 8   Total_Stops      10682 non-null  object
 9   Additional_Info  10683 non-null  object
 10  Price            10683 non-null  int64
dtypes: int64(1), object(10)
memory usage: 918.2+ KB

In [29]:
# check the statistics of the dataset
df.describe()

              Price
count  10683.000000
mean    9087.064121
std     4611.359167
min     1759.000000
25%     5277.000000
50%     8372.000000
75%    12373.000000
max    79512.000000

In [30]:
# missing values in the dataset
df.isnull().sum()

Airline            0
Date_of_Journey    0
Source             0
Destination        0
Route              1
Dep_Time           0
Arrival_Time       0
Duration           0
Total_Stops        1
Additional_Info    0
Price              0
dtype: int64

In [31]:
df.shape

(10683, 11)

In [32]:
df.columns

Index(['Airline', 'Date_of_Journey', 'Source', 'Destination', 'Route',
       'Dep_Time', 'Arrival_Time', 'Duration', 'Total_Stops',
       'Additional_Info', 'Price'],
      dtype='object')

In [33]:
df.dtypes

Airline            object
Date_of_Journey    object
Source             object
Destination        object
Route              object
Dep_Time           object
Arrival_Time       object
Duration           object
Total_Stops        object
Additional_Info    object
Price               int64
dtype: object

In [34]:
# Step 4: Data Preprocessing

# drop the missing values
df.dropna(inplace=True)

In [35]:
df.isna().sum()

Airline            0
Date_of_Journey    0
Source             0
Destination        0
Route              0
Dep_Time           0
Arrival_Time       0
Duration           0
Total_Stops        0
Additional_Info    0
Price              0
dtype: int64

In [36]:
df.duplicated().sum()

220

In [37]:
# Drop the duplicated value 
df.drop_duplicates(inplace=True)

In [38]:
# handled the first column Date_of_Journey

df['Date_of_Journey'] = pd.to_datetime(df['Date_of_Journey'],errors='coerce')

df['Day'] = df['Date_of_Journey'].dt.day
df['Month'] = df['Date_of_Journey'].dt.month
df['Year'] = df['Date_of_Journey'].dt.year

C:\Users\ssart\AppData\Local\Temp\ipykernel_11184\1885351099.py:3: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['Date_of_Journey'] = pd.to_datetime(df['Date_of_Journey'],errors='coerce')

In [39]:
#drop the Date_of_Journey column
df.drop('Date_of_Journey',axis=1,inplace=True)

In [42]:
df.columns

Index(['Airline', 'Source', 'Destination', 'Route', 'Dep_Time', 'Arrival_Time',
       'Duration', 'Total_Stops', 'Price', 'Day', 'Month', 'Year'],
      dtype='object')

In [41]:
#  drop Additional_Info
df.drop('Additional_Info',axis=1,inplace=True)

In [43]:
df['Dep_Time']

0        22:20
1        05:50
2        09:25
3        18:05
4        16:50
         ...
10678    19:55
10679    20:45
10680    08:20
10681    11:30
10682    10:55
Name: Dep_Time, Length: 10462, dtype: object

In [44]:
# extract the departure hour and minute from the Dep_Time column
df['Dep_Hour'] = pd.to_datetime(df['Dep_Time']).dt.hour
df['Dep_Minute'] = pd.to_datetime(df['Dep_Time']).dt.minute

C:\Users\ssart\AppData\Local\Temp\ipykernel_11184\3459823997.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Dep_Hour'] = pd.to_datetime(df['Dep_Time']).dt.hour
C:\Users\ssart\AppData\Local\Temp\ipykernel_11184\3459823997.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Dep_Minute'] = pd.to_datetime(df['Dep_Time']).dt.minute

In [46]:
df.drop('Dep_Time',axis=1,inplace=True)

In [47]:
df.columns

Index(['Airline', 'Source', 'Destination', 'Route', 'Arrival_Time', 'Duration',
       'Total_Stops', 'Price', 'Day', 'Month', 'Year', 'Dep_Hour',
       'Dep_Minute'],
      dtype='object')

In [ ]:
# handle the Arrival_Time column
df['Arrival_Time'] = df['Arrival_Time'].str.split(' ',expand=True)[0]
df['Arrival_Time'] = pd.to_datetime(df['Arrival_Time'],errors='coerce')

df['Arrival_Hour'] = df['Arrival_Time'].dt.hour
df['Arrival_Minute'] = df['Arrival_Time'].dt.minute

C:\Users\ssart\AppData\Local\Temp\ipykernel_11184\823798218.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Arrival_Time'] = pd.to_datetime(df['Arrival_Time'],errors='coerce')

In [52]:
df.drop('Arrival_Time',axis=1,inplace=True)

In [56]:
# handled the Duration column
df['Duration'] = df['Duration'].str.replace('h','').str.replace('m','')
df['Duration_Hours'] = df['Duration'].str.split(' ',expand=True)[0]
df['Duration_Minutes'] = df['Duration'].str.split(' ',expand=True)[1]

In [61]:
df['Duration_Minutes'].fillna(0,inplace=True)

In [63]:
df.drop('Duration',axis=1,inplace=True)

In [64]:
df.head()

,Airline,Source,Destination,Route,Total_Stops,Price,Day,Month,Year,Dep_Hour,Dep_Minute,Arrival_Hour,Arrival_Minute,Duration_Hours,Duration_Minutes
0,IndiGo,Banglore,New Delhi,BLR → DEL,non-stop,3897,24,3,2019,22,20,1,10,2,50
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,2 stops,7662,1,5,2019,5,50,13,15,7,25
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,2 stops,13882,9,6,2019,9,25,4,25,19,0
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,1 stop,6218,12,5,2019,18,5,23,30,5,25
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,1 stop,13302,1,3,2019,16,50,21,35,4,45

In [67]:
# check the unique values in  the total_stops column
df['Total_Stops'].unique()

array([0, 2, 1, 3, 4], dtype=int64)

In [66]:
#handled the Total_Stops column

df['Total_Stops'] = df['Total_Stops'].map({'non-stop':0,'1 stop':1,'2 stops':2,'3 stops':3,'4 stops':4})

In [69]:
df.head()

,Airline,Source,Destination,Route,Total_Stops,Price,Day,Month,Year,Dep_Hour,Dep_Minute,Arrival_Hour,Arrival_Minute,Duration_Hours,Duration_Minutes
0,IndiGo,Banglore,New Delhi,BLR → DEL,0,3897,24,3,2019,22,20,1,10,2,50
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,2,7662,1,5,2019,5,50,13,15,7,25
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,2,13882,9,6,2019,9,25,4,25,19,0
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,1,6218,12,5,2019,18,5,23,30,5,25
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,1,13302,1,3,2019,16,50,21,35,4,45

In [70]:
# handled the Route column

df['Route_1'] = df['Route'].str.split('→',expand=True)[0]
df['Route_2'] = df['Route'].str.split('→',expand=True)[1]
df['Route_3'] = df['Route'].str.split('→',expand=True)[2]
df['Route_4'] = df['Route'].str.split('→',expand=True)[3]
df['Route_5'] = df['Route'].str.split('→',expand=True)[4]

In [72]:
df.drop('Route',axis=1,inplace=True)

In [73]:
df.head()

,Airline,Source,Destination,Total_Stops,Price,Day,Month,Year,Dep_Hour,Dep_Minute,Arrival_Hour,Arrival_Minute,Duration_Hours,Duration_Minutes,Route_1,Route_2,Route_3,Route_4,Route_5
0,IndiGo,Banglore,New Delhi,0,3897,24,3,2019,22,20,1,10,2,50,BLR,DEL,None,None,None
1,Air India,Kolkata,Banglore,2,7662,1,5,2019,5,50,13,15,7,25,CCU,IXR,BBI,BLR,None
2,Jet Airways,Delhi,Cochin,2,13882,9,6,2019,9,25,4,25,19,0,DEL,LKO,BOM,COK,None
3,IndiGo,Kolkata,Banglore,1,6218,12,5,2019,18,5,23,30,5,25,CCU,NAG,BLR,None,None
4,IndiGo,Banglore,New Delhi,1,13302,1,3,2019,16,50,21,35,4,45,BLR,NAG,DEL,None,None

Airline
Jet Airways                          3700
IndiGo                               2043
Air India                            1694
Multiple carriers                    1196
SpiceJet                              815
Vistara                               478
Air Asia                              319
GoAir                                 194
Multiple carriers Premium economy      13
Jet Airways Business                    6
Vistara Premium economy                 3
Trujet                                  1
Name: count, dtype: int64