In [32]:
# 1. Load the CSV using Pandas and display the first 10 rows.
import pandas as pd
df = pd.read_csv("C:\\Users\\ntt\\Downloads\\customer_data - customer_data.csv")
df

,Customer ID,Age,income_usd,credit Score,tenure_years,monthly_visits,satisfaction,City,customer_segment,gender,is_active,churn_flag,signup_date,lead_source,notes_text
0,CUST-01861,45.86741673,28198.41033,660.5629176,5.274076,5.0,3.382150,Pune,consumer,NaN,Yes,No,2026-03-11,Referral,NaN
1,CUST-00354,47.76516428,61312.83129,838 pts,5.632826,9.0,NaN,Hyderabad,Consumer,Male,NaN,No,NaN,website,follow-up needed
2,CUST-01334,NaN,44199.67124,613.1327754,NaN,8.0,4.195157,Mumbai,Consumer,m,Yes,No,2024-09-20,Email,NaN
3,CUST-00906,62.72357805,56259.90961,720.2369862,2.029634,4.0,NaN,Chennai,Enterprise,m,N,No,2023-07-12,Website,normal
4,CUST-01290,NaN,31238.64196,549.1832523,2.648626,5.0,3.117326,Mumbai,Enterprise,Male,Yes,No,2024-08-06,NaN,???
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,CUST-01131,27.26951178,79436.89335,633.9740063,14.007477,NaN,3.556073,Bengaluru,Consumer,M,no,No,2024-02-26,email,normal
1996,CUST-01295,41.09168505,39912.37991,701.7201056,0.673289,8.0,2.963094,Pune,SMB,m,N,Yes,2024-08-11,Website,good
1997,CUST-00861,26.21576696,24522.26545,647.7993363,2.026485,12.0,3.079259,Hyderabad,SMB.,F,yes,No,2023-05-27,WEB,???
1998,CUST-01460,42.3 years,84103.61056,521 pts,7.168156,5.0,3.579652,Hyderabad,SMB,NaN,N,Yes,2025-01-26,Email,ok
1999,CUST-01127,59.25609491,53723.87392,576.7390735,9.720663,NaN,1.100520,Pune,Consumer,NaN,yes,No,2024-02-22,???,good

In [5]:
# 2. Check the number of rows and columns in the dataset.
df.shape

(2000, 15)

In [17]:
# 3. Display all column names and identify which column names contain
# leading/trailing spaces or inconsistent capitalization.
df.columns
for col in df.columns:
    print(repr(col))

'Customer ID'
'Age'
'income_usd'
'credit Score'
'tenure_years'
'monthly_visits'
'satisfaction'
'City'
'customer_segment'
'gender'
'is_active'
'churn_flag'
'signup_date'
'lead_source'
'notes_text'

In [16]:
# 4. Check the data type of every column using Pandas.
df.dtypes

Customer ID          object
Age                  object
income_usd           object
credit Score         object
tenure_years        float64
monthly_visits      float64
satisfaction        float64
City                 object
customer_segment     object
gender               object
is_active            object
churn_flag           object
signup_date          object
lead_source          object
notes_text           object
dtype: object

In [18]:
# 5. Calculate the number and percentage of missing values in every column.
df.isnull().sum()

Customer ID          20
Age                 331
income_usd          440
credit Score        360
tenure_years        258
monthly_visits      280
satisfaction        399
City                300
customer_segment    380
gender              240
is_active           340
churn_flag          160
signup_date         240
lead_source         420
notes_text          656
dtype: int64

In [23]:
df.isnull.sum()/.df(len)*100

SyntaxError: invalid syntax (3540739817.py, line 1)

In [35]:
# 6. Find the rows where Customer ID is missing.
df[df["Customer ID"].isna()]

,Customer ID,Age,income_usd,credit Score,tenure_years,monthly_visits,satisfaction,City,customer_segment,gender,is_active,churn_flag,signup_date,lead_source,notes_text
162,NaN,18,61780.99213,715.4452325,10.137001,5.0,3.179153,Delhi,UNKNOWN,Female,NaN,No,2021-04-22,website,follow-up needed
226,NaN,18,58188.80528,737.9284458,15.655950,12.0,3.330254,Chennai,Consumer,Female,Y,NaN,2022-03-18,Referral,normal
300,NaN,NaN,93665.74378,703.9692987,12.723292,7.0,NaN,Pune,SMB,Female,1,No,NaN,Email,follow-up needed
421,NaN,29.6 years,NaN,641.3441152,8.940646,5.0,3.687539,NaN,Consumer,Female,1,No,2021-12-05,Unknown,NaN
770,NaN,20.39545706,92366.06753,767.8048841,4.524943,3.0,4.358065,Mumbai,Enterprise,f,N,No,2021-09-05,???,NaN
821,NaN,46.41996378,81119.71831,597.3307848,1.076200,5.0,4.346306,Delhi,consumer,f,1,Yes,2022-12-26,Email,NaN
876,NaN,36.57634009,76629.87047,699.109735,4.977078,6.0,2.700057,Mumbai,consumer,M,N,Yes,2021-07-01,referral,good
993,NaN,47.54933612,NaN,NaN,0.693710,4.0,3.659781,NaN,Enterprise,NaN,NaN,No,2024-07-09,Referral,late payment
1023,NaN,NaN,34219.41505,NaN,3.779121,4.0,3.529211,Hyderabad,NaN,M,N,No,2023-07-05,Google Ads,ok
1188,NaN,28.97406958,NaN,744 pts,7.947965,8.0,2.379383,Hyderabad,Consumer,f,Yes,No,2026-06-06,NaN,urgent
1202,NaN,42.23152645,35310.77625,684.8618643,2.465432,6.0,4.979391,Delhi,SMB,m,1,No,2024-10-10,google_ads,late payment
1212,NaN,56.44358785,"$99,697",749.3298384,3.743193,6.0,NaN,NaN,NaN,M,Y,Yes,2024-07-18,WEB,NaN
1248,NaN,34.60645101,96811.19575,798.1150352,1.551247,5.0,3.288656,Mumbai,SMB.,M,N,No,2023-09-16,Social,follow-up needed
1338,NaN,26.5 years,"$89,682",692.0794813,1.877392,4.0,3.783551,Pune,Consumer,m,N,No,2023-12-04,WEB,NaN
1346,NaN,46.22898842,60122.78196,684.8548451,3.837557,2.0,4.267750,Mumbai,consumer,F,N,Yes,2023-01-01,referral,follow-up needed
1448,NaN,18,NaN,628.337014,7.137356,5.0,NaN,Pune,Enterprise,Female,no,NaN,2024-08-25,Google Ads,NaN
1451,NaN,47.20187446,28270.08329,549.3662455,3.019237,6.0,3.441021,Hyderabad,SMB,m,yes,Yes,2023-10-12,Unknown,good
1462,NaN,49.99203599,58348.28529,511.5806801,2.775352,NaN,NaN,Mumbai,SMB,Female,no,No,2024-07-07,NaN,NaN
1564,NaN,42.96550781,"$64,045",561 pts,4.549291,4.0,3.513904,Chennai,Consumer,m,No,No,03/08/2023,Email,NaN
1652,NaN,33.27510593,37475.10034,NaN,4.345689,11.0,-999.000000,Mumbai,SMB,f,NaN,NaN,2022-02-15,Social,ok

In [38]:
# 7. Remove leading/trailing whitespace from all column names and convert them
# to lowercase with underscores.
df.columns.str.rstrip().str.lower()
df.columns

Index(['Customer ID', 'Age', 'income_usd', 'credit Score', 'tenure_years',
       'monthly_visits', 'satisfaction', 'City', 'customer_segment', 'gender',
       'is_active', 'churn_flag', 'signup_date', 'lead_source', 'notes_text'],
      dtype='object')

In [42]:
# 8. Identify duplicate Customer ID values and count how many duplicates exist.
df["Customer ID"].duplicated,inplace=False

TypeError: cannot unpack non-iterable bool object

In [44]:
 df["Customer Id"].duplicated().sum()

KeyError: 'Customer Id'

In [45]:
# 10.Find all unique values in the customer_segment column and identify
# inconsistent categories such as Consumer, consumer, consumer , etc.
df["customer_segment"].unique()

array(['consumer', 'Consumer', 'Enterprise', 'SMB', nan, 'SMB.',
       'UNKNOWN'], dtype=object)

In [46]:
# 11.Clean the customer_segment column by standardizing capitalization and
# whitespace.
df["customer_segment"] = df["customer_segment"].astype(str).str.rstrip().str.title()
print(df["customer_segment"])

0         Consumer
1         Consumer
2         Consumer
3       Enterprise
4       Enterprise
           ...
1995      Consumer
1996           Smb
1997          Smb.
1998           Smb
1999      Consumer
Name: customer_segment, Length: 2000, dtype: object

In [55]:
# 12.Find all unique values in the gender column and convert them into consistent
# categories such as Male and Female.
df["gender"] = df["gender"].astype(str).str.strip().str.lower()
df["gender"] = df["gender"].replace({
    "nan":"Male",
    "male":"Male",
    "m":"Male",
    "m":"Female",
    "m":"Female",
    "f":"Female",})
print(df["gender"].unique())

['Male' 'female']

In [58]:
# 13.Clean the is_active column so values such as Yes, yes, Y, 1 become 1, and
# No, no, N, 0 become 0.
df["is_active"] = df["is_active"].astype(str).str.strip().str.lower()
print(df["is_active"])
df["is_active"].replace({
    "yes":1,
    "yes":1,
    "n":1,
    "No":0,
    "n":0,
    "no":0,})
print(df["is_active"])

0       yes
1       nan
2       yes
3         n
4       yes
       ...
1995     no
1996      n
1997    yes
1998      n
1999    yes
Name: is_active, Length: 2000, dtype: object
0       yes
1       nan
2       yes
3         n
4       yes
       ...
1995     no
1996      n
1997    yes
1998      n
1999    yes
Name: is_active, Length: 2000, dtype: object

In [63]:
# 14.Convert the churn_flag column from categorical values (Yes/No) into a binary
# numerical column (1/0).
df["churn_flag"] = df["churn_flag"].astype(str).str.strip().str.lower()
df["churn_flag"]
df["churn_flag"].replace({
    "yes":1,
    "no":0
})
df["churn_flag"] = pd.to_numeric(df["churn_flag"], errors="coerce")
print(df["churn_flag"].unique())

[nan]